### ISSUE TITLE
Key docker.api Unsupported item key

### ISSUE THREAD

**Issue by asm19** [vivanov-dp/zabbix-docker-template#3] opened 2020-10-07 16:18 UTC
Hello,

I can't understand what the problem is, I made the configuration as it is in the Setup but the key docker.api[{$DOCKER.SOCKET},_ping] gives error "Unsupported item key". I don't change the default macro: /var/run/docker.sock

![image](https://user-images.githubusercontent.com/1648981/95358458-ff020e80-08c0-11eb-8fbe-8733bd2e0bc7.png)

Procedure:
cp docker_template.conf /etc/zabbix/zabbix_agentd.d/
sudo usermod -a -G docker zabbix
restart Zabbix Agent
import docker_template_agent1.xml into Zabbix templates
This will create a template named Template App Docker - Agent 1 attach the new template to hosts to start monitoring
configure macros as needed
{$DOCKER.SOCKET} has to point to docker's unix socket (default is /var/run/docker.sock)

![image](https://user-images.githubusercontent.com/1648981/95358374-e3970380-08c0-11eb-87da-c0beb3bb1380.png)

Can you help?

Thank you

**Comment by vivanov-dp** [comment] 2020-10-07 17:59
Hi @asm19 

This is really strange since everything else seems to work.
Can you tell me which version of docker are you using ?
Also try the following command on the host you are monitoring: `curl -s --unix-socket /var/run/docker.sock http://latest/_ping` , as user zabbix if possible, and paste the result here

**Comment by asm19** [comment] 2020-10-07 18:24
It's ok with user zabbix:

![image](https://user-images.githubusercontent.com/1648981/95371811-9cb20980-08d2-11eb-8df6-1b5ed115ad04.png)

Docker version 19.03.13, build 4484c46d9d

My zabbix version: 5.0.4

**Comment by vivanov-dp** [comment] 2020-10-07 18:53
Alright, the docker API call works, so the problem is somewhere within the Zabbix setup.

There are log files both on the client and on the server, usually named `/var/log/zabbix/zabbix_agentd.log` and `/var/log/zabbix/zabbix_server.log`. Could you take a look and find anything that mentions the item __Docker: Ping__ or something like __became unsupported__ ? There should be a reason for it specified there.

**Comment by asm19** [comment] 2020-10-07 19:52
Already checked, nothing "obvious":

Zabbix server, /var/log/zabbix/zabbix_server.log:

863410:20201007:204545.747 discovery rule "XXXXXXXXXX:docker.containers.list[{$DOCKER.SOCKET}]" became not supported: Unsupported item key.
863411:20201007:204545.747 discovery rule "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},images/json]" became not supported: Unsupported item key.
863249:20201007:204636.443 item "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},_ping]" became not supported: Unsupported item key.
863252:20201007:204640.458 item "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},info]" became not supported: Unsupported item key.
863250:20201007:204641.465 item "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},system/df]" became not supported: Unsupported item key.
863250:20201007:204641.465 item "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},version]" became not supported: Unsupported item key.

On the client I don't have any log with "docker".

**Comment by asm19** [comment] 2020-10-07 20:01
Uncomment this line:

UnsafeUserParameters=1

Now work but have others problems:

863251:20201007:205626.029 item "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},_ping]" became supported
863252:20201007:205639.755 item "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},info]" became supported
863252:20201007:205639.755 item "XXXXXXXXXX:docker.root_dir" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.nfd" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.containers.total" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.name" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.info.text" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.goroutines" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.debug.enabled" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.containers.stopped" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.containers.running" became not supported: Preprocessing failed for:
863252:20201007:205639.755 item "XXXXXXXXXX:docker.containers.paused" became not supported: Preprocessing failed for:
863250:20201007:205640.756 item "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},system/df]" became supported
863250:20201007:205640.756 item "XXXXXXXXXX:docker.volumes_size" became not supported: Preprocessing failed for:
863250:20201007:205640.756 item "XXXXXXXXXX:docker.images_size" became not supported: Preprocessing failed for:
863250:20201007:205640.756 item "XXXXXXXXXX:docker.containers_size" became not supported: Preprocessing failed for:
863250:20201007:205640.756 item "XXXXXXXXXX:docker.layers_size" became not supported: Preprocessing failed for:
863250:20201007:205641.766 item "XXXXXXXXXX:docker.info.version_text" became not supported: Preprocessing failed for:
863250:20201007:205641.766 item "XXXXXXXXXX:docker.version" became not supported: Preprocessing failed for:
863250:20201007:205641.766 item "XXXXXXXXXX:docker.api_version" became not supported: Preprocessing failed for:
863250:20201007:205641.766 item "XXXXXXXXXX:docker.api[{$DOCKER.SOCKET},version]" became supported

Example:
![image](https://user-images.githubusercontent.com/1648981/95381551-37fdab80-08e0-11eb-9cdf-6af6c6da8d91.png)

**Comment by vivanov-dp** [comment] 2020-10-09 08:35
Hmm .. yes, `UnsafeUserParameters=1` might be required - I'm running with it switched on and haven't considered it at all, since I always check any parameters and mods that I add to the zabbix client from external sources.

The message you get now means that Zabbix is not receiving the proper JSON objects from the docker API.
Can you get the JSON value from one of the items that misbehave, for example `Template App Docker - Agent 1 - Gamesrv: Docker: Get info` ? 
Go to the item in the host configuration (not the template), and click `test`, then `get value`

![items](https://user-images.githubusercontent.com/19204135/95558239-9a5cc600-0a1e-11eb-9665-e137217f47c9.png)

See if the received value is a valid JSON and contains the properties that are mentioned in the error messages.
The `Get Info` item should return something looking like this:

```JSON
{
    "ID": "KVIT:YKKL:DBX7:YTM2:SSHB:BFLQ:GX5J:MP37:QXNY:SRRY:PCN2:6DQH",
    "Containers": 13,
    "ContainersRunning": 13,
    "ContainersPaused": 0,
    "ContainersStopped": 0,
    "Images": 6,
    "Driver": "overlay2",
    "DriverStatus": [
        [
            "Backing Filesystem",
            "extfs"
        ],
        [
            "Supports d_type",
            "true"
        ],
        [
            "Native Overlay Diff",
            "true"
        ]
    ],
    "SystemStatus": null,
    "Plugins": {
        "Volume": [
            "local"
        ],
        "Network": [
            "bridge",
            "host",
            "macvlan",
            "null",
            "overlay"
        ],
        "Authorization": null,
        "Log": [
            "awslogs",
            "fluentd",
            "gcplogs",
            "gelf",
            "journald",
            "json-file",
            "local",
            "logentries",
            "splunk",
            "syslog"
        ]
    },
    "MemoryLimit": true,
    "SwapLimit": true,
    "KernelMemory": true,
    "CpuCfsPeriod": true,
    "CpuCfsQuota": true,
    "CPUShares": true,
    "CPUSet": true,
    "IPv4Forwarding": true,
    "BridgeNfIptables": true,
    "BridgeNfIp6tables": true,
    "Debug": false,
    "NFd": 131,
    "OomKillDisable": true,
    "NGoroutines": 152,
    "SystemTime": "2020-10-09T08:27:40.106333171Z",
    "LoggingDriver": "json-file",
    "CgroupDriver": "cgroupfs",
    "NEventsListener": 1,
    "OSType": "linux",
    "Architecture": "x86_64",
    "IndexServerAddress": "https://index.docker.io/v1/",
    "RegistryConfig": {
        "AllowNondistributableArtifactsCIDRs": [],
        "AllowNondistributableArtifactsHostnames": [],
        "InsecureRegistryCIDRs": [
            "127.0.0.0/8"
        ],
        "IndexConfigs": {
            "docker.io": {
                "Name": "docker.io",
                "Mirrors": [],
                "Secure": true,
                "Official": true
            }
        },
        "Mirrors": []
    },
    "NCPU": 2,
    "MemTotal": 8141873152,
    "GenericResources": null,
    "DockerRootDir": "/var/lib/docker",
    "HttpProxy": "",
    "HttpsProxy": "",
    "NoProxy": "",
    "Name": "ip-10-10-3-95.ec2.internal",
    "Labels": [],
    "ExperimentalBuild": false,
    "ServerVersion": "18.09.9-ce",
    "ClusterStore": "",
    "ClusterAdvertise": "",
    "Runtimes": {
        "runc": {
            "path": "runc"
        }
    },
    "DefaultRuntime": "runc",
    "Swarm": {
        "NodeID": "",
        "NodeAddr": "",
        "LocalNodeState": "inactive",
        "ControlAvailable": false,
        "Error": "",
        "RemoteManagers": null
    },
    "LiveRestoreEnabled": false,
    "Isolation": "",
    "InitBinary": "docker-init",
    "ContainerdCommit": {
        "ID": "894b81a4b802e4eb2a91d1ce216b8817763c29fb",
        "Expected": "894b81a4b802e4eb2a91d1ce216b8817763c29fb"
    },
    "RuncCommit": {
        "ID": "2b18fe1d885ee5083ef9f0838fee39b62d653e30",
        "Expected": "2b18fe1d885ee5083ef9f0838fee39b62d653e30"
    },
    "InitCommit": {
        "ID": "fec3683",
        "Expected": "fec3683"
    },
    "SecurityOptions": [
        "name=seccomp,profile=default"
    ],
    "Warnings": null
}
```

You can check it vs the docker API directly by using curl: `curl -s --unix-socket /var/run/docker.sock http://latest/info` for example, but I suspect that works just fine and the problem is with something in the Zabbix configuration.

**Comment by asm19** [comment] 2020-10-09 08:53
Hello @vivanov-dp,

In Discovery Rules if I run one, for example "Template App Docker - Agent 1: Containers discovery" I have this errors:

![image](https://user-images.githubusercontent.com/1648981/95562473-1b629000-0a14-11eb-8ab7-ccfbe1fc4a7c.png)

In the Items, for example for "Template App Docker - Agent 1: Docker: Get info: Docker: Name":

![image](https://user-images.githubusercontent.com/1648981/95562623-4d73f200-0a14-11eb-81fe-13d2bd286d2b.png)

It seems that zabbix cannot generate the json file. If I run `curl -s --unix-socket /var/run/docker.sock http://latest/info
` in the client host works without problems.

![image](https://user-images.githubusercontent.com/1648981/95563367-341f7580-0a15-11eb-940f-086655a6d29f.png)

**Comment by vivanov-dp** [comment] 2020-10-09 09:15
Can you try it with zabbix-get ?
On your server (or the proxy, if you use one):
`zabbix_get -s IP.IP.IP.IP -k docker.api[/var/run/docker.sock,info]`

**Comment by asm19** [comment] 2020-10-09 09:16
No errors or result:

![image](https://user-images.githubusercontent.com/1648981/95565754-88782480-0a18-11eb-8695-3a36364c6f15.png)

**Comment by vivanov-dp** [comment] 2020-10-09 09:27
This means that the Zabbix agent doesn't return the value at all - it should look exactly the same as when you call curl directly.
Try to find what is wrong with the agent .. I will try to think of something to help later, if you don't find a fix in the meantime

**Comment by asm19** [comment] 2020-10-09 09:33
It's strange because I have the last version:

![image](https://user-images.githubusercontent.com/1648981/95567411-d130dd00-0a1a-11eb-8e30-23086b8d6a33.png)

Passive mode.

**Comment by Scandinav21** [comment] 2020-10-14 09:29
I have the similar problem.
All items is unsupported but ping is down.

`zabbix_get -s IP.IP.IP.IP -k docker.api[/var/run/docker.sock,info]` returns nothing

zabbix agent is the latest version

**Comment by asm19** [comment] 2020-10-14 09:58
Yes, I have the similar problem.

**Comment by vivanov-dp** [comment] 2020-10-14 11:49
Hi @Scandinav21, @asm19 
It's some kind of configuration problem with the host that's running the Zabbix Agent.
Are you sure you have added user `zabbix` to the `docker` group and `/var/run/docker.sock` is readable by the group ?

Test with `sudo -u zabbix curl -s --unix-socket /var/run/docker.sock http://latest/info`
( @asm19 : `curl -u zabbix ...` does something different - it authenticates with user `zabbix` to the server it is contacting (docker API in this case), but what you want to do is run the `curl` process as user `zabbix`, sorry for not catching that earlier )

If this returns a result, zabbix_get should also return it

**Comment by asm19** [comment] 2020-10-14 11:56
@vivanov-dp 

![image](https://user-images.githubusercontent.com/1648981/95985465-8b11ba00-0e1c-11eb-83d7-82fc96663c2a.png)

With zabbix_get -s IP.IP.IP.IP -k docker.api[/var/run/docker.sock,info] from zabbix server I don't have any result.

**Comment by vivanov-dp** [comment] 2020-10-14 12:03
Is it possible that zabbix-agent runs as different user on your system ? I'm unable to replicate your problem, and if that's not it, I'm out of ideas ...

**Comment by asm19** [comment] 2020-10-14 12:09
Run with root user in Zabbix server:

![image](https://user-images.githubusercontent.com/1648981/95986596-30795d80-0e1e-11eb-9256-f79d5f626ac4.png)

In docker server:

![image](https://user-images.githubusercontent.com/1648981/95986720-569efd80-0e1e-11eb-86cc-9a0ccf7b4d39.png)

I cannot understand the problem also.

**Comment by Scandinav21** [comment] 2020-10-14 13:05
Acnkoweledge, @asm19 `sudo -u zabbix curl -s --unix-socket /var/run/docker.sock http://latest/info` returns data, its okey, zabbix_agent is running by zabbix user.
So me to out of ideas.

@asm19 whats the name of your system?
Im using CentOS 7 and 8.

**Comment by asm19** [comment] 2020-10-14 13:09
@Scandinav21 
CentOS Linux release 8.2.2004 (Core)

**Comment by Scandinav21** [comment] 2020-10-15 07:36
@asm19 I've figured out when run zabbix_agent from root the issue has gone. So maybe zabbix user has no some kind rights

UPD. It looks like I've found workaround:
1. [start zabbix_agent from root](https://www.zabbix.com/documentation/current/manual/appendix/install/run_agent_as_root)
2. Undo previous changes and restart zabbig_agent from zabbix user and it works,

but may be somebody can find the issue core.

**Comment by asm19** [comment] 2020-10-15 12:55
@Scandinav21 
You change it in Zabbix Server or in Docker server? The first time I change in docker server without result, in the second time I try in Zabbix Server but without result also.

**Comment by Scandinav21** [comment] 2020-10-15 13:28
@asm19 I've found the solution.
In my case it was SELinux.
I've found in audit logs _SELinux is preventing /usr/bin/curl from connectto access on the unix_stream_socket /run/docker.sock_
Then I used `sealert -a /var/log/audit/audit.log` and found the solution
```
ausearch -c 'curl' --raw | audit2allow -M my-curl
semodule -i my-curl.pp
```
And it works for me.

**Comment by asm19** [comment] 2020-10-15 13:51
In zabbix server, right? I will check

**Comment by Scandinav21** [comment] 2020-10-15 13:51
> 
> 
> In zabbix server, right?

In server where docker and zabbix_agent is running

**Comment by asm19** [comment] 2020-10-15 14:01
You are right, the problem is in SELinux. I solved the problem with your suggestion.

**Comment by vivanov-dp** [comment] 2020-10-16 07:57
@Scandinav21 Great work! Thanks for sharing your solution

**Comment by vivanov-dp** [comment] 2020-10-18 19:44
I'm closing this, since the problem seems to have been solved. 
I'm sorry I can't confirm it on my side, but all hosts I have are running without SELinux.
I have left a link to this issue in the documentation, so people can find it.

**Closed as completed by vivanov-dp** 2020-10-18 19:44 UTC
